### PR TITLE
Add a favicon

### PR DESCRIPTION
**Pull request by sauloperez**
I used the C from the Coopdevs logo. Anything else we add looks too noisy at this size.

Screenshot from 2019-10-02 16-03-37

### CODE REVIEW

**Review by enricostano — APPROVED** [review]

**Review by danypr92 — APPROVED** [review]
:clap: :clap: :clap: :clap:

**Comment by enricostano** [comment]
Would be nice to have the same in community.coopdevs.org :grimacing:

**Comment by sauloperez** [comment]
Any idea how should we do that? I guess we also need to add the .ico at the
root of site

Missatge de Enrico Stano <notifications@github.com> del dia dc., 2 d’oct.
2019 a les 19:15:

**Comment by enricostano** [comment]
IIRC, you can do that from the UI. Just upload the `.ico` file, I guess.

**Pull request merged**
