### PR TITLE
fix(homepage): removes the hyphen from homepages and the 404 page (reference #76)

### LINKED ISSUE #76: Remove "-" from homepage title
We use "-" in title for subtitle, for example Blog post title would be "Coopdevs - Blog post title" in home we want to remove it.

2019-10-03-121733_1960x2160_scrot

### PR DESCRIPTION
**Pull request by agawish**
# What I did

- Removed the `-` from Homepage (both languages)
- Removed the `-` from the 404 page

# How I did it

- Checked out `master` branch
- Fixed the code
- Profit

# How to verify it

- Run `jekyll`
 
# A picture of a cute animal
animal-967657_640

Fixes #76

### CODE REVIEW

**Comment by agawish** [comment]
@sseerrggii Are you happy with the changes?

**Comment by sauloperez** [comment]
Thanks a lot for your contribution @agawish !

My apologies but @ir4hul already fixed it in #77. There are issues you can work on from other projects we have. Take a look at https://github.com/search?q=org%3Acoopdevs+is%3Aopen+is%3Aissue+archived%3Afalse+label%3Ahacktoberfest&type=Issues. Most of them are related to Ruby and Rails. I hope that's not a problem for you.

We'll surely create more issues in here so stay tuned as well.

**Comment by agawish** [comment]
No problems @sauloperez

**Comment by sauloperez** [comment]
Btw @agawish , https://github.com/openfoodfoundation/openfoodnetwork/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest has also shit tons of things you can help with. The list of issues never gets below 300 🙈

**Comment by agawish** [comment]
@sauloperez just wondering as the solution provided here https://github.com/coopdevs/coopdevs.github.io/pull/77 will not actually solve the homepage problem as it is a static page. Ofcourse feel free to use this code as help for @ir4hul

**Pull request closed without merging**
